[package]
name = "tendermint-primitives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# crates.io
anyhow = { version = "1.0.64", default-features = false }
derive_more = { version = "0.99.17", default-features = false, features = ["display"] }

# ibc
ibc = { path = "../../../ibc/modules", features = [] }
ibc-proto = { path = "../../../ibc/proto" }
pallet-ibc = { path = "../../../contracts/pallet-ibc" }

# Tendermint
tendermint = { workspace = true }
tendermint-rpc   = { workspace = true }
tendermint-proto = { workspace = true }
tendermint-light-client = { workspace = true }
tendermint-light-client-verifier = { workspace = true }
ics07-tendermint = { path = "../../../light-clients/ics07-tendermint" }